languageCode = "zh-cn"
languageName = "简体中文"
weight = 1
title = "eallion's Blog"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "Jan 2, 2006"
  logo = "images/eallion.svg"
  # secondaryLogo
  description = "机会总是垂青于有准备的人！"
  copyright = "© 2006 - { year } <span class='inline-block'><a href='/copyright/' target='_blank'>eallion.com</a> All Rights Reserved</span>. <span class='inline-block'><a href='https://beian.miit.gov.cn/' target='_blank'>浙ICP备16031768号-2</a></span>"

