languageCode = "zh-cn"
languageName = "简体中文"
weight = 1
title = "大大的小蜗牛"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "Jan 2, 2006"
  # logo = "images/logo.png"
  # secondaryLogo
  description = "机会总是垂青于有准备的人！"
  copyright = "© 2006 - { year } <span class='inline-block'><a href='/copyright/' target='_blank'>eallion.com</a> All Rights Reserved</span>. <span class='inline-block'><a href='https://beian.miit.gov.cn/' target='_blank'>浙ICP备16031768号-2</a></span>"

[author]
  name = "大大的小蜗牛"
  image = "images/eallion.png"
  headline = "机会总是垂青于有准备的人！"
  bio = "机会总是垂青于有准备的人！"
  links = [
    { email = "mailto:eallions@gmail.com" },
    { mastodon = "https://e5n.cc/@eallion" },
    { github = "https://github.com/eallion" },
    { x-twitter = "https://x.com/eallion" },
    { steam = "https://steamcommunity.com/id/eallion" },
    { keybase = "https://keybase.io/eallion" },
  ]
