# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "åšå®¢"
  pageRef = "blog"
  weight = 10

[[main]]
  name = "å˜€å’•<sup>ğŸ”¥</sup>"
  pageRef = "mastodon"
  weight = 11

[[main]]
  name = "ä¹¦å½±éŸ³"
  pageRef = "media"
  weight = 12

[[main]]
  name = "é‡Œç¨‹ç¢‘"
  pageRef = "milestone"
  weight = 13

[[main]]
  name = "æ›´å¤š"
  weight = 20

[[main]]
  name = "ç»Ÿè®¡"
  parent = "æ›´å¤š"
  pageRef = "stats"
  weight = 21

# [[main]]
#   name = "Steam"
#   parent = "æ›´å¤š"
#   pageRef = "steam"
#   weight = 22

[[main]]
  name = "éšæ‰‹æ‹"
  parent = "æ›´å¤š"
  pageRef = "album"
  weight = 30

[[main]]
  name = "LOL äº”æ€"
  parent = "æ›´å¤š"
  pageRef = "penta"
  weight = 40

[[main]]
  name = "å¥½ç‰©åˆ†äº«"
  parent = "æ›´å¤š"
  pageRef = "goods"
  weight = 50

[[main]]
  name = "ç‰ˆæƒä¿¡æ¯"
  parent = "æ›´å¤š"
  pageRef = "copyright"
  weight = 60

[[main]]
  name = "éšç§æ”¿ç­–"
  parent = "æ›´å¤š"
  pageRef = "privacy-policy"
  weight = 70

[[main]]
  name = "å‹æƒ…é“¾æ¥"
  pageRef = "links"
  weight = 90

[[main]]
  name = "å…³äº"
  pageRef = "about"
  weight = 100

# [[main]]
#   name = "Test"
#   pageRef = "pagTest"
#   weight = 1000

# [[main]]
#   identifier = "twitter"
#   pre = "x-twitter"
#   url = "https://x.com/eallion"
#   weight = 200

# [[main]]
#   identifier = "mastodon"
#   pre = "mastodon"
#   weight = 300
#   url = "https://e5n.cc/@eallion"

# [[main]]
#   identifier = "github"
#   pre = "github"
#   url = "https://github.com/eallion/eallion.com"
#   weight = 400

# [[main]]
#   identifier = "deepwiki"
#   pre = "deepwiki"
#   url = "https://deepwiki.com/eallion/eallion.com"
#   weight = 500


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

# [[footer]]
#   name = "<div id='notbyai' class='notbyai written'></div>"
#   url = "https://notbyai.fyi"
#   weight = 10
#
# [[footer]]
#   name = "<div id='nonbot' class='nonbot'></div>"
#   url = "https://nonbot.org/pledged/view/9cefed7c-dc57-4832-84ec-197314fda979"
#   weight = 11

[[footer]]
  name = "ç»Ÿè®¡"
  pageRef = "stats"
  weight = 50

[[footer]]
  name = "é‡Œç¨‹ç¢‘"
  pageRef = "milestone"
  weight = 60

[[footer]]
  name = "ç‰ˆæƒä¿¡æ¯"
  pageRef = "copyright"
  weight = 61

[[footer]]
  name = "éšç§æ”¿ç­–"
  pageRef = "privacy-policy"
  weight = 62

[[footer]]
  name = "å…³äº"
  pageRef = "about"
  weight = 90

[[footer]]
  name = "Status <svg width='1rem' height='1rem' viewBox='0 0 32 32'><path fill='currentColor' d='M18 5v2h5.563L11.28 19.281l1.438 1.438L25 8.437V14h2V5zM5 9v18h18V14l-2 2v9H7V11h9l2-2z'></path></svg>"
  url = "https://status.eallion.com/"
  weight = 91

[[footer]]
  pre = "rss"
  name = "RSS"
  url = "https://www.eallion.com/rss"
  weight = 99

[[footer]]
  name = "llms.txt"
  pageRef = "/llms.txt"
  weight = 999
