# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "博客"
  pageRef = "blog"
  weight = 10

[[main]]
  name = "嘀咕"
  pageRef = "mastodon"
  weight = 11

# [[main]]
#   name = "书影音"
#   pageRef = "media"
#   weight = 12
#
# [[main]]
#   name = "更多"
#   weight = 20

[[main]]
  name = "统计"
  # parent = "更多"
  pageRef = "stats"
  weight = 21

[[main]]
  name = "里程碑"
  pageRef = "milestone"
  weight = 22

# [[main]]
#   name = "Steam"
#   parent = "更多"
#   pageRef = "steam"
#   weight = 23
#
# [[main]]
#   name = "随手拍"
#   parent = "更多"
#   pageRef = "album"
#   weight = 30
#
# [[main]]
#   name = "LOL 五杀"
#   parent = "更多"
#   pageRef = "penta"
#   weight = 40
#
# [[main]]
#   name = "好物分享"
#   parent = "更多"
#   pageRef = "goods"
#   weight = 50

[[main]]
  name = "友情链接"
  # parent = "更多"
  pageRef = "links"
  weight = 70

# [[main]]
#   name = "版权信息"
#   # parent = "更多"
#   pageRef = "copyright"
#   weight = 80
#
# [[main]]
#   name = "隐私政策"
#   # parent = "更多"
#   pageRef = "privacy-policy"
#   weight = 90

[[main]]
  name = "关于"
  pageRef = "about"
  weight = 100

# [[main]]
#   name = "Test"
#   pageRef = "pagTest"
#   weight = 1000

# [[main]]
#   identifier = "twitter"
#   pre = "x-twitter"
#   url = "https://x.com/eallion"
#   weight = 200

# [[main]]
#   identifier = "mastodon"
#   pre = "mastodon"
#   weight = 300
#   url = "https://e5n.cc/@eallion"

# [[main]]
#   identifier = "github"
#   pre = "github"
#   url = "https://github.com/eallion/eallion.com"
#   weight = 400

# [[main]]
#   identifier = "deepwiki"
#   pre = "deepwiki"
#   url = "https://deepwiki.com/eallion/eallion.com"
#   weight = 500


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

# [[footer]]
#   name = "<div id='notbyai' class='notbyai written'></div>"
#   url = "https://notbyai.fyi"
#   weight = 10
#
# [[footer]]
#   name = "<div id='nonbot' class='nonbot'></div>"
#   url = "https://nonbot.org/pledged/view/9cefed7c-dc57-4832-84ec-197314fda979"
#   weight = 11

[[footer]]
  name = "统计"
  pageRef = "stats"
  weight = 50

[[footer]]
  name = "里程碑"
  pageRef = "milestone"
  weight = 60

[[footer]]
  name = "友情链接"
  pageRef = "links"
  weight = 61

[[footer]]
  name = "版权信息"
  pageRef = "copyright"
  weight = 62

[[footer]]
  name = "隐私政策"
  pageRef = "privacy-policy"
  weight = 63

[[footer]]
  name = "关于"
  pageRef = "about"
  weight = 90

[[footer]]
  name = "Status <svg width='1rem' height='1rem' viewBox='0 0 32 32'><path fill='currentColor' d='M18 5v2h5.563L11.28 19.281l1.438 1.438L25 8.437V14h2V5zM5 9v18h18V14l-2 2v9H7V11h9l2-2z'></path></svg>"
  url = "https://status.eallion.com/"
  weight = 91

[[footer]]
  pre = "rss"
  name = "RSS"
  url = "https://www.eallion.com/rss"
  weight = 99

[[footer]]
  name = "llms.txt"
  url = "https://www.eallion.com/llms.txt"
  weight = 999
