# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "blowfish" # blowfish, avocado, fire, ocean, forest, princess, neon, bloody, terminal, marvel, noir, autumn, congo, slate
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true

enableA11y = true
enableSearch = true
enableCodeCopy = true

mainSections = ["posts", "blog"]

showViews = false
showLikes = false

# robots = ""

disableImageZoom = true
disableImageOptimization = true
disableImageOptimizationMD = true
disableTextInHeader = false
# backgroundImageWidth = 1200

defaultBackgroundImage = "/images/interstellar.webp"
defaultFeaturedImage = "/images/featured-default.webp"

hotlinkFeatureImage = true
imagePosition = "50% 50%"

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

[header]
  layout = "fixed-fill-blur" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[author]
  name = "Charles Chin"
  image = "https://images.eallion.com/avatar/eallion.png!hugo.webp"
  imageQuality = 96
  headline = "机会总是垂青于有准备的人！"
  bio = "机会总是垂青于有准备的人！"
  links = [
    { email = "mailto:eallion.s+blog@gmail.com" },
    { keyoxide = "https://keyoxide.org/E685DDDDDDDDDDDD" },
    { mastodon = "https://e5n.cc/@eallion" },
    { github = "https://github.com/eallion" },
    { steam = "https://steamcommunity.com/id/eallion" }
  ]

[homepage]
  layout = "custom" # valid options: page, profile, hero, card, background, custom
  homepageImage = "/images/interstellar.webp" # used in: hero, and card
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/blog"
  cardView = true
  showSummary = false
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background
  disableHeroImageFilter = false # only used when layout equals hero

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateOnlyInArticle = false
  showDateUpdated = false
  showAuthor = false
  showAuthorBottom = false
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  editURL = "https://github.com/eallion/eallion.com/tree/main/content"
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = false
  relatedContentLimit = 3
  showTaxonomies = true
  showCategoryOnly = false
  showAuthorsBadges = false
  showWordCount = true
  showComments = true
  sharingLinks = [ "twitter", "facebook", "mastodon", "reddit", "whatsapp", "telegram", "linkedin", "pinterest", "bluesky", "email"]
  showZenMode = true

[list]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = false
  showSummary = true
  showViews = false
  showLikes = false
  showTableOfContents = true
  showCards = false
  orderByWeight = false
  groupByYear = true
  cardView = false
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = []
  excludedSections = ["milestone"]

[layouts]
  [layouts.milestone]
    single = true
    merge = false

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  cardView = false

[term]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false

# [firebase]
  # apiKey = "AIzaSyB5tqlqDky77Vb4Tc4apiHV4hRZI18KGiY"
  # authDomain = "blowfish-21fff.firebaseapp.com"
  # projectId = "blowfish-21fff"
  # storageBucket = "blowfish-21fff.appspot.com"
  # messagingSenderId = "60108104191"
  # appId = "1:60108104191:web:039842ebe1370698b487ca"
  # measurementId = "G-PEDMYR1V0K"

# [fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

# [umamiAnalytics]
  # websiteid = ""
  # domain = ""
  # dataDomains = ""
  # scriptName = ""
  # enableTrackEvent = true

# [selineAnalytics]
  # token = "XXXXXX"
  # enableTrackEvent = false

# [buymeacoffee]
  # identifier = "nunocoracao"
  # globalWidget = true
  # globalWidgetMessage = ""
  # globalWidgetColor = "#FFDD00"
  # globalWidgetPosition = "right"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
  google = "9Mvl_9FEM5JphVmp-u9ljtlChFohWuBBFjlSS89QKVU"
  bing = "68A03C00DAFAD54E3739A8D372D9371B"
  yandex = "ff49a8cfbbaad423"
  pinterest = "b9e3534b99f9bd82f3b8688a1fa122a8"
  baidu = "ZWIiTFJWJkGQ11ZJ"
  so = "05afe845fd64ce6966deadce74479b5b"
  sogou = "SZM7r2UEOz"
  fediverse ="@eallion@e5n.cc"

[rssnext]
  feedId = "42331815237783556"
  userId = "41909911558319104"

# [advertisement]
  # adsense = ""
