name: Upload Mastodon to Algolia

on:
#  push:
#    branches:
#      - main
#  schedule:
#    - cron: 0 16 * * *
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 0

      - name: Fetch Memos JSON
        run: |
          data_url="https://api.eallion.com/mastodon/api/v1/accounts/111136231674527355/statuses?limit=20&exclude_replies=true&exclude_reblogs=true"
          output_file="output.json"
          curl -s "$data_url" | jq '.[] | {objectID:  (.id | tostring), date: .created_at, content: (.content | gsub("<[^>]*>";"")), uri, title: (.content | gsub("<[^>]*>";"") | rtrimstr("\n") | .[ :20])}' > "$output_file"
          jq -s '.' "$output_file" > mastodon.json

      - name: Algolia uploader
        uses: wangchucheng/algolia-uploader@master
        with:
          app_id: ${{ secrets.ALGOLIA_APPID }}
          admin_key: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          index_name: mastodon
          index_file_path: mastodon.json
